name: My First Workflow

on: [push, fork]

jobs: 
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: checkout repo
             uses: actions/checkout@v6

            - name: Welcome message
              run: echo "My first github actions"

            - name: List files available in this repo
              run: ls

            - name: Read file
              run: cat README.md